name        'puppet-scala'
version     '0.1.2'
source      'git://github.com/kayak/puppet-scala.git'
author      'Neil Hanlon'
summary     'Module for installing scala'
description 'Install scala and sbt'
license     'Apache License, Version 2.0'
dependency  'maestrodev/wget'
dependency  'puppetlabs/stdlib'
